# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c898891f4947a8ff2b0fc200e5a4df2f12893519c8d21ae8577e94b4caf4fb58d4a1a5b2a5abb1cc2fe193a07968c527660a1ad4d181c593aa6c9857c34dce5

test:
  secret_key_base: b2ab624f723bf2b54cd13c7f7c9a8f17a5e1c44ae57472b69994ea4683b34593e53b574fb333f7a24e9dee18521ad7c68f58c61e78a0a12e2cb0345e5a4d1d91

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
